//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiCameBack.Website.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ForgotPassword {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForgotPassword() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxiCameBack.Website.App_LocalResources.ForgotPassword", typeof(ForgotPassword).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string btn_send {
            get {
                return ResourceManager.GetString("btn_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại trong hệ thống. Xin nhập lại..
        /// </summary>
        public static string ERR_MESSAGE_NO_EXIST {
            get {
                return ResourceManager.GetString("ERR_MESSAGE_NO_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string forgot_form {
            get {
                return ResourceManager.GetString("forgot_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string forgot_title {
            get {
                return ResourceManager.GetString("forgot_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string plc_email {
            get {
                return ResourceManager.GetString("plc_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đã gửi đến email của bạn thông tin thay đổi mật khẩu..
        /// </summary>
        public static string SUC_MESSAGE_SEND_EMAIL {
            get {
                return ResourceManager.GetString("SUC_MESSAGE_SEND_EMAIL", resourceCulture);
            }
        }
    }
}
