//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiCameBack.Website.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxiCameBack.Website.App_LocalResources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © CopyRight FreshGarden Team.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa điều kiện.
        /// </summary>
        public static string btn_clear {
            get {
                return ResourceManager.GetString("btn_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string btn_register {
            get {
                return ResourceManager.GetString("btn_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string btn_search_title {
            get {
                return ResourceManager.GetString("btn_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi vị trí.
        /// </summary>
        public static string btn_switch_title {
            get {
                return ResourceManager.GetString("btn_switch_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải đồng ý với điều khoản của chúng tôi.
        /// </summary>
        public static string customer_agree {
            get {
                return ResourceManager.GetString("customer_agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng không được để trống.
        /// </summary>
        public static string customer_fullname_rqr {
            get {
                return ResourceManager.GetString("customer_fullname_rqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại khách hàng không được để trống.
        /// </summary>
        public static string customer_phone_rqr {
            get {
                return ResourceManager.GetString("customer_phone_rqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm taxi đường dài giá rẻ... Địa điểm, địa chỉ số,bản đồ vệ tinh Vietnam Maps - Phát triển bởi FreshGarden Team.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taxi, taxi trong, dia diem, địa điểm, tim duong, tìm đường, tìm địa chỉ, tìm địa điểm, diadiem,vietnam mapss.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên.
        /// </summary>
        public static string lbl_administator {
            get {
                return ResourceManager.GetString("lbl_administator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string lbl_CarType {
            get {
                return ResourceManager.GetString("lbl_CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Chỗ.
        /// </summary>
        public static string lbl_CarType4 {
            get {
                return ResourceManager.GetString("lbl_CarType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Chỗ.
        /// </summary>
        public static string lbl_CarType7 {
            get {
                return ResourceManager.GetString("lbl_CarType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string lbl_CustomerName {
            get {
                return ResourceManager.GetString("lbl_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại KH.
        /// </summary>
        public static string lbl_CustomerPhone {
            get {
                return ResourceManager.GetString("lbl_CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài xế.
        /// </summary>
        public static string lbl_DriverName {
            get {
                return ResourceManager.GetString("lbl_DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại liên hệ.
        /// </summary>
        public static string lbl_DriverPhone {
            get {
                return ResourceManager.GetString("lbl_DriverPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến.
        /// </summary>
        public static string lbl_endpoint {
            get {
                return ResourceManager.GetString("lbl_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách xe đi các tỉnh.
        /// </summary>
        public static string lbl_Find_Car_By_Location {
            get {
                return ResourceManager.GetString("lbl_Find_Car_By_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm taxi.
        /// </summary>
        public static string lbl_FindCar {
            get {
                return ResourceManager.GetString("lbl_FindCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định vị.
        /// </summary>
        public static string lbl_Locate {
            get {
                return ResourceManager.GetString("lbl_Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí đón khách.
        /// </summary>
        public static string lbl_NearPos {
            get {
                return ResourceManager.GetString("lbl_NearPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string lbl_note {
            get {
                return ResourceManager.GetString("lbl_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biến số xe.
        /// </summary>
        public static string lbl_PlateNumber {
            get {
                return ResourceManager.GetString("lbl_PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ phải trả 50% cho chuyến đi này.
        /// </summary>
        public static string lbl_reg_note {
            get {
                return ResourceManager.GetString("lbl_reg_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Đơn giá: {0} đ/1km).
        /// </summary>
        public static string lbl_reg_note2 {
            get {
                return ResourceManager.GetString("lbl_reg_note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký lộ trình.
        /// </summary>
        public static string lbl_register {
            get {
                return ResourceManager.GetString("lbl_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí xe.
        /// </summary>
        public static string lbl_register_taxi {
            get {
                return ResourceManager.GetString("lbl_register_taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình.
        /// </summary>
        public static string lbl_Route {
            get {
                return ResourceManager.GetString("lbl_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        public static string lbl_SearchResult {
            get {
                return ResourceManager.GetString("lbl_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có kết quả nào được tìm thấy.
        /// </summary>
        public static string lbl_SearchResult_Content {
            get {
                return ResourceManager.GetString("lbl_SearchResult_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp trực tuyến.
        /// </summary>
        public static string lbl_sp_online {
            get {
                return ResourceManager.GetString("lbl_sp_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian xuất hành.
        /// </summary>
        public static string lbl_startdate {
            get {
                return ResourceManager.GetString("lbl_startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đi.
        /// </summary>
        public static string lbl_startpoint {
            get {
                return ResourceManager.GetString("lbl_startpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        public static string lbl_UserGuide {
            get {
                return ResourceManager.GetString("lbl_UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;margin-bottom:6px&quot; class=&quot;pdboxms3&quot;&gt;Ứng dụng Bản đồ Việt Nam trực tuyến Online, tìm đường đi nhanh và gần nhất, xem bản đồ các tỉnh thành như Hà Nội, Sài Gòn, TP.HCM, Đà Nẵng, Cần Thơ, Hải Phòng, Nha Trang, Bình Dương, Đà Lạt… chỉ đường đi nhanh nhất, ngắn nhất đến các địa điểm, địa chỉ, vị trí,khu vui chơi, khu du lịch, giải trí, khách sạn, nhà hàng trên khắp Việt Nam. Bản đồ vệ tinh, danh bạ địa chỉ số tiện dụng nhất hiện nay.&lt;/h2&gt;&lt;p class=&quot;pdboxms3&quot;&gt;Nhập địa chỉ muốn tìm vào khung tìm kiếm trê [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lbl_UserGuideContent {
            get {
                return ResourceManager.GetString("lbl_UserGuideContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn tìm vị trí.
        /// </summary>
        public static string lbl_UserGuideHeader {
            get {
                return ResourceManager.GetString("lbl_UserGuideHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập điểm đến.
        /// </summary>
        public static string plh_EndPoint {
            get {
                return ResourceManager.GetString("plh_EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ và tên.
        /// </summary>
        public static string plh_FullName {
            get {
                return ResourceManager.GetString("plh_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập vị trí đón.
        /// </summary>
        public static string plh_NearPos {
            get {
                return ResourceManager.GetString("plh_NearPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ghi chú.
        /// </summary>
        public static string plh_note {
            get {
                return ResourceManager.GetString("plh_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        public static string plh_PhoneNumber {
            get {
                return ResourceManager.GetString("plh_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập điểm bắt đầu.
        /// </summary>
        public static string plh_StartPoint {
            get {
                return ResourceManager.GetString("plh_StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thời gian đi.
        /// </summary>
        public static string plh_TimeStart {
            get {
                return ResourceManager.GetString("plh_TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taxiquayve.vn.
        /// </summary>
        public static string Site_name {
            get {
                return ResourceManager.GetString("Site_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm taxi giá rẻ. Địa điểm, địa chỉ số,bản đồ vệ tinh Vietnam Maps.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
