//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiCameBack.Website.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxiCameBack.Website.App_LocalResources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy chuyến.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ điều kiện.
        /// </summary>
        public static string btn_delete_con {
            get {
                return ResourceManager.GetString("btn_delete_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận chuyến.
        /// </summary>
        public static string btn_received {
            get {
                return ResourceManager.GetString("btn_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy.
        /// </summary>
        public static string cancel_status {
            get {
                return ResourceManager.GetString("cancel_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn.
        /// </summary>
        public static string customer_action {
            get {
                return ResourceManager.GetString("customer_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất hành.
        /// </summary>
        public static string customer_datecreate {
            get {
                return ResourceManager.GetString("customer_datecreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận.
        /// </summary>
        public static string customer_datereceive {
            get {
                return ResourceManager.GetString("customer_datereceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến.
        /// </summary>
        public static string customer_end_pos {
            get {
                return ResourceManager.GetString("customer_end_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí đón.
        /// </summary>
        public static string customer_near_pos {
            get {
                return ResourceManager.GetString("customer_near_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string customer_phone {
            get {
                return ResourceManager.GetString("customer_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng đặt xe.
        /// </summary>
        public static string customer_reg_type {
            get {
                return ResourceManager.GetString("customer_reg_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đi.
        /// </summary>
        public static string customer_start_pos {
            get {
                return ResourceManager.GetString("customer_start_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string customer_status {
            get {
                return ResourceManager.GetString("customer_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string customer_type {
            get {
                return ResourceManager.GetString("customer_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài xế đặt xe quay về.
        /// </summary>
        public static string driver_reg_type {
            get {
                return ResourceManager.GetString("driver_reg_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch trình đã bị hủy. Bạn không thể nhận lịch trình.
        /// </summary>
        public static string notification_cancel {
            get {
                return ResourceManager.GetString("notification_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy lịch trình thất bại.
        /// </summary>
        public static string notification_cancel_err {
            get {
                return ResourceManager.GetString("notification_cancel_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy lịch trình thành công.
        /// </summary>
        public static string notification_cancel_suc {
            get {
                return ResourceManager.GetString("notification_cancel_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể hủy lịch trình này khi lịch trình đã bị hủy rồi..
        /// </summary>
        public static string notification_cancel_was_cancel {
            get {
                return ResourceManager.GetString("notification_cancel_was_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch trình không tồn tại. Bạn không thể nhận lịch trình..
        /// </summary>
        public static string notification_not_found {
            get {
                return ResourceManager.GetString("notification_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể nhận lịch trình mà tài xế khác tạo.
        /// </summary>
        public static string notification_not_receive_other {
            get {
                return ResourceManager.GetString("notification_not_receive_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã nhận lịch trình rồi. Bạn không thể nhận lại lần nữa..
        /// </summary>
        public static string notification_not_receive_twice {
            get {
                return ResourceManager.GetString("notification_not_receive_twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận lịch trình thất bại.
        /// </summary>
        public static string notification_receive_err {
            get {
                return ResourceManager.GetString("notification_receive_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận lịch trình thành công..
        /// </summary>
        public static string notification_receive_suc {
            get {
                return ResourceManager.GetString("notification_receive_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể nhận lịch trình này khi lịch trình đã được nhận..
        /// </summary>
        public static string notification_receive_was_receive {
            get {
                return ResourceManager.GetString("notification_receive_was_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ.
        /// </summary>
        public static string pending_status {
            get {
                return ResourceManager.GetString("pending_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận.
        /// </summary>
        public static string receive_status {
            get {
                return ResourceManager.GetString("receive_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc khách hàng.
        /// </summary>
        public static string search_title {
            get {
                return ResourceManager.GetString("search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách khách hàng.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
