//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiCameBack.Website.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Register {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxiCameBack.Website.App_LocalResources.Register", typeof(Register).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string btn_register {
            get {
                return ResourceManager.GetString("btn_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên có độ dài tối đa 20 ký tự.
        /// </summary>
        public static string fullname_length {
            get {
                return ResourceManager.GetString("fullname_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi đồng ý với các điều khoản.
        /// </summary>
        public static string lbl_agree_term {
            get {
                return ResourceManager.GetString("lbl_agree_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại đăng nhập.
        /// </summary>
        public static string lbl_login_back {
            get {
                return ResourceManager.GetString("lbl_login_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy chọn tài khoản Gmail để đăng ký.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu có độ dài từ 8 đến 20 kí tự.
        /// </summary>
        public static string password_length {
            get {
                return ResourceManager.GetString("password_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string plc_email {
            get {
                return ResourceManager.GetString("plc_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string plc_fullname {
            get {
                return ResourceManager.GetString("plc_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string plc_password {
            get {
                return ResourceManager.GetString("plc_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string plc_phone {
            get {
                return ResourceManager.GetString("plc_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string plc_re_password {
            get {
                return ResourceManager.GetString("plc_re_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu nhập lại không khớp.
        /// </summary>
        public static string re_password_match {
            get {
                return ResourceManager.GetString("re_password_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại, bạn hãy thử lại lần nữa..
        /// </summary>
        public static string register_failed {
            get {
                return ResourceManager.GetString("register_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ TÀI KHOẢN TÀI XẾ.
        /// </summary>
        public static string register_form {
            get {
                return ResourceManager.GetString("register_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxiQuayVe.
        /// </summary>
        public static string register_logo {
            get {
                return ResourceManager.GetString("register_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản thành công ! Xin đợi email xác nhận.
        /// </summary>
        public static string register_success {
            get {
                return ResourceManager.GetString("register_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản.
        /// </summary>
        public static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa đồng ý với các điều khoản.
        /// </summary>
        public static string rqr_agree_term {
            get {
                return ResourceManager.GetString("rqr_agree_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        public static string rqr_email {
            get {
                return ResourceManager.GetString("rqr_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được để trống.
        /// </summary>
        public static string rqr_fullname {
            get {
                return ResourceManager.GetString("rqr_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        public static string rqr_password {
            get {
                return ResourceManager.GetString("rqr_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được để trống.
        /// </summary>
        public static string rqr_phone {
            get {
                return ResourceManager.GetString("rqr_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu không được để trống.
        /// </summary>
        public static string rqr_re_password {
            get {
                return ResourceManager.GetString("rqr_re_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã được sử dụng để đăng ký..
        /// </summary>
        public static string uniq_email {
            get {
                return ResourceManager.GetString("uniq_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string valid_email {
            get {
                return ResourceManager.GetString("valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không hợp lệ.
        /// </summary>
        public static string valid_password {
            get {
                return ResourceManager.GetString("valid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        public static string valid_phone {
            get {
                return ResourceManager.GetString("valid_phone", resourceCulture);
            }
        }
    }
}
